### ISSUE TITLE
The raw data is not accessible

### ISSUE THREAD

**Issue by arash-sh** [teamdiva2019/ProjectDIVA#1]
Hi, 
The chesapeake and florida raw data are not publicly available under the given link, access request did not help either. Is there a way to get the data otherwise?
If not, can it be replaced with some other data (what type, dimensions, format, etc. ) ?

Thanks,

**Comment by eeSquared** [comment]
Hello,
Our google drive folder was private since no one has ever tried to build this before- go ahead and try now!

**Comment by arash-sh** [comment]
Thanks, it worked!
